CREATE TABLE DEPT_HW AS SELECT * FROM DEPT;

SELECT * FROM DEPT_HW;
-- Q1. 두 세션에서 실행되는 순서별 SQL 명령어 확인
-- 세션 A
UPDATE DEPT_HW
    SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 30;

SELECT * FROM DEPT_HW;

-- 세션 B
SELECT * FROM DEPT_HW;
