-- Q1. 급여가 2000 초과인 사원들의 부서 정보, 사원 정보 출력
-- SQL-99 이전 방식 사용
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
AND SAL > 2000
ORDER BY DEPTNO, SAL ASC;
-- SQL-99 방식 사용
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E LEFT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL > 2000
ORDER BY DEPTNO, SAL ASC;

-- Q2. 각 부서별 평균 급여, 최대 급여, 최소 급여, 사원수 출력
-- SQL-99 이전 방식 사용
SELECT E.DEPTNO, FLOOR(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(E.EMPNO) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO(+)
GROUP BY E.DEPTNO
ORDER BY E.DEPTNO ASC;

-- SQL-99 방식 사용
SELECT E.DEPTNO, FLOOR(AVG(E.SAL)), MAX(E.SAL), MIN(E.SAL), COUNT(E.EMPNO) AS CNT
FROM EMP E LEFT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
GROUP BY E.DEPTNO
ORDER BY E.DEPTNO ASC;

-- Q3. 모든 부서 정보와 사원 정보를 부서 번호, 사원 이름순으로 정렬하여 출력
-- SQL-99 이전 방식 사용
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY DEPTNO, ENAME ASC;
-- SQL-99 방식 사용
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E RIGHT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY DEPTNO, ENAME ASC;

-- Q4. 모든 부서 정보, 사원 정보, 급여 등급 정보, 각 사원의 직속 상관의 정보를 부서 번호, 사원 번호 순서로 정렬하여 출력
-- SQL-99 이전 방식 사용
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.MGR, E.SAL, D.DEPTNO AS DEPTNO_1, S.LOSAL, S.HISAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO ASC;

-- SQL-99 방식 사용
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.MGR, E.SAL, D.DEPTNO AS DEPTNO_1, S.LOSAL, S.HISAL, S.GRADE, E.MGR AS MGR_EMPNO, E.MGR AS MGR_ENAME
FROM EMP E LEFT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO), SALGRADE S
ORDER BY D.DEPTNO, E.EMPNO ASC;

























--8장 연습문제 239p
-- 2. 각 부서별 평균 급여, 최대 급여, 사원 수 출력하기
SELECT D.DEPTNO, D.DNAME, E.SAL
       --AVG(E.SAL) AS AVG_SAL,
       --MAX(E.SAL) AS MAX_SAL,
       --MIN(E.SAL AS MIN_SAL,
       --COUNT(*) AS CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
ORDER BY D.DEPTNO, D.DNAME;