--Q11. 1982년에 입사한 사원 출력하기
SELECT *
FROM EMP
WHERE HIREDATE LIKE '1982%';

SELECT *
FROM EMP
WHERE HIREDATE LIKE '82%'; -- 날짜형식에 따라 바뀔 수 있음.

SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '1982/01/01' AND '1982/12/31';

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') = '1982';

SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '82/01/01' and '82/12/31';

SELECT * 
FROM EMP 
WHERE HIREDATE >= '1982-01-01' AND HIREDATE <= '1982-12-31';

SELECT *
FROM EMP
WHERE HIREDATE BETWEEN TO_DATE('1982-01-01', 'YYYY-MM-DD') 
               AND TO_DATE('1982-12-31', 'YYYY-MM-DD') ;

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') LIKE '1982';

SELECT *
FROM EMP
WHERE HIREDATE >= TO_DATE('1982/01/01', 'YYYY-MM-DD')
AND HIREDATE < TO_DATE('1983/01/01', 'YYYY-MM-DD');

SELECT *
FROM EMP
WHERE HIREDATE >= '1982/01/01'
AND  HIREDATE <= '1982/12/31';

-- Q12. 이름이 'F'로 시작하는 사원 출력하기
SELECT *
FROM EMP
WHERE ENAME LIKE 'F%';

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, 1, 1) = 'F';

SELECT *
FROM EMP
WHERE INSTR(ENAME, 'F') = 1;

SELECT *
FROM EMP
WHERE ENAME >= 'F' AND ENAME <'G';

-- Q13. 이름이 'M'이 포함되어 있는 사원 출력하기
SELECT *
FROM EMP
WHERE ENAME LIKE '%M%';

SELECT *
FROM EMP
WHERE INSTR(ENAME,'M') > 0;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE NOT INSTR(UPPER(ENAME), 'M') = 0;

-- Q14. 이름이 'N'으로 끝나는 사원 출력하기
SELECT *
FROM EMP
WHERE ENAME LIKE '%N';

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, -1, 1) = 'N';

SELECT *
FROM EMP
WHERE INSTR(ENAME,'N')=LENGTH(ENAME);

SELECT * 
FROM EMP
WHERE SUBSTR(ENAME,LENGTH(ENAME))='N';

SELECT *
FROM EMP
WHERE ENAME IN (
    SELECT ENAME
    FROM EMP
    WHERE ENAME LIKE '%N'
);

-- Q15. 이름의 두 번째 글자가 'A'인 사원 출력하기
SELECT *
FROM EMP
WHERE SUBSTR(ENAME, 2, 1) = 'A';

SELECT *
FROM EMP
WHERE ENAME LIKE '_A%';

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE INSTR(ENAME,'A') = 2;


--Q16. 이름의 세 번째 글자가 'A'인 사원 출력하기
SELECT *
FROM EMP
WHERE ENAME LIKE '__A%';

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, 3, 1) = 'A';

SELECT * 
FROM EMP
WHERE INSTR(ENAME, 'A', 3, 1) = 3;

-- Q17. 덧셈 연산자를 이용하여 모든 사원에 대해서 300의 급여 인상을 계산한 후 사원의 이름, 급여, 인상된 급여를 출력하시오.
SELECT ENAME, SAL, SAL + 300 AS 인상된급여
FROM EMP;

SELECT ENAME, SAL + 300 AS "인상된급여" 
FROM EMP;

-- Q18. 사원의 이름, 급여, 연간 총수입을 총 수입이 많은 것부터 작은 순으로 출력하시오. 연간 총수입은 월급에 12를 곱한 후 100의 상여금을 더해서 계산하시오.
SELECT ENAME, SAL, (SAL * 12) + 100 AS 연간총수입
FROM EMP
ORDER BY SAL * 12 + 100 DESC;

SELECT ENAME, SAL, (SAL * 12) + 100 AS 연간총수입
FROM EMP
ORDER BY 연간총수입 DESC;

-- Q19. 급여가 2000을 넘는 사원의 이름과 급여를 급여가 많은 것부터 작은 순으로 출력하시오.
SELECT ENAME, SAL
FROM EMP
WHERE SAL > 2000
ORDER BY SAL DESC;

SELECT ENAME, SAL
FROM EMP
WHERE NOT SAL <= 2000
ORDER BY SAL DESC;

-- Q20. 사원번호가 7788인 사원의 이름과 부서번호 출력
SELECT ENAME, DEPTNO
FROM EMP
WHERE EMPNO = 7788;

SELECT ENAME, DEPTNO
FROM
    (SELECT * 
     FROM EMP 
     WHERE EMPNO = 7788) EMP;
     
