-- EMP, SALGRADE, DEPT 테이블 사용합니다.
-- 문제와 SQL문을 함께 줌 채팅(DM)으로 보내주세요.

-- Q1. 급여가 1500이상인 사원 출력하기
SELECT *
FROM EMP
WHERE SAL >= 1500;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL >= 1500;

SELECT * 
FROM EMP
WHERE SAL > 1500
OR SAL = 1500;

SELECT *
FROM EMP
MINUS
SELECT *
FROM EMP
WHERE SAL < 1500;

-- Q2. 10번 부서 소속 사원 출력
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT *
FROM EMP
MINUS
SELECT *
FROM EMP
WHERE DEPTNO <> 10;

SELECT *
FROM EMP
WHERE DEPTNO IN (10);

SELECT *
FROM EMP
WHERE DEPTNO NOT IN (20, 30, 40);

SELECT * FROM EMP
WHERE NOT DEPTNO = 20
AND NOT DEPTNO = 30
AND NOT DEPTNO = 40;

SELECT *
FROM EMP
WHERE DEPTNO < 20;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO 
FROM EMP 
WHERE NOT(DEPTNO != 10);

SELECT *
FROM EMP
MINUS
SELECT *
FROM EMP
WHERE DEPTNO = 20 OR DEPTNO = 30 OR DEPTNO = 40;

-- Q3. 이름이 SCOTT인 사원 출력하기
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE ENAME = 'SCOTT';

-- 서브쿼리 이용하기
SELECT *
FROM EMP
WHERE EMPNO = (SELECT EMPNO
                FROM EMP
                WHERE ENAME = 'SCOTT');
                
SELECT * 
FROM EMP
WHERE UPPER(ENAME)='SCOTT';

SELECT *
FROM EMP
MINUS
SELECT *
FROM EMP
WHERE UPPER(ENAME) != 'SCOTT';

SELECT * 
FROM EMP
WHERE ENAME LIKE 'S____'
AND ENAME LIKE '_C___'
AND ENAME LIKE '__O__'
AND ENAME LIKE '___T_'
AND ENAME LIKE '____T';

-- Q4. 입사일이 '1981/01/01' 이전인 사원만 출력하기
SELECT *
FROM EMP
WHERE HIREDATE <= '1981-01-01';

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE HIREDATE <= '1981/01/01';

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE HIREDATE < '1981/01/01';

SELECT * 
FROM EMP 
WHERE HIREDATE < TO_DATE('1981-01-01', 'YYYY/MM/DD');

SELECT * 
FROM EMP 
WHERE HIREDATE < TO_DATE('01/01/1981', '/DD/MM/YYYY');

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE HIREDATE <= TO_DATE('1981/01/01', 'RRRR/MM/DD');

SELECT * 
FROM EMP
WHERE HIREDATE < TO_DATE('1981-01-01', 'YYYY-MM-DD');

-- Q5. 부서번호가 10이고 직급이 'MANAGER'인 사원만 출력하기
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO = 10
AND JOB = 'MANAGER';

SELECT *
FROM EMP
WHERE DEPTNO = 10 
AND UPPER(JOB) = 'MANAGER';

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO = 10
INTERSECT
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE JOB = 'MANAGER';

DESC EMP;
DESC DEPT;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, E.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 10
AND JOB = 'MANAGER';

-- Q6. 부서번호가 10이거나 직급이 'MANAGER'인 사원만 출력하기
SELECT *
FROM EMP
WHERE DEPTNO = 10
OR JOB = 'MANAGER';

-- 셀프조인 사용
SELECT DISTINCT(E.EMPNO), E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 10
OR JOB = 'MANAGER';

SELECT * FROM EMP 
WHERE DEPTNO = 10 
OR UPPER(JOB) = 'MANAGER';

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO = 10
OR JOB = 'MANAGER';

SELECT *
FROM EMP
WHERE DEPTNO=10 
UNION
SELECT *
FROM EMP
WHERE JOB='MANAGER';

--Q7. 부서번호가 10이 아닌 사원 출력하기
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO <> 10;

SELECT *
FROM EMP
MINUS
SELECT *
FROM EMP
WHERE DEPTNO = 10;
                 
SELECT * 
FROM EMP 
WHERE DEPTNO != 10;

SELECT * 
FROM EMP 
WHERE DEPTNO ^= 10;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE DEPTNO != 10;

SELECT * 
FROM EMP 
WHERE NOT DEPTNO = 10;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE NOT DEPTNO = 10;

SELECT *
FROM EMP 
WHERE NOT(DEPTNO = 10);

SELECT *
FROM EMP
WHERE DEPTNO IN (20,30,40);

SELECT *
FROM EMP 
MINUS
SELECT *
FROM EMP 
WHERE DEPTNO = 10;

SELECT *
FROM EMP
WHERE
    CASE
        WHEN DEPTNO = 10 THEN 'FALSE'
        ELSE 'TRUE'
    END = 'TRUE';
    
--Q8. 급여가 1000에서 1500 사이인 사원 출력하기
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL BETWEEN 1000 AND 1500;

SELECT *
FROM EMP
WHERE SAL >= 1000
AND SAL <= 1500;

SELECT *
FROM EMP
WHERE NOT(SAL < 1000 OR SAL > 1500);

SELECT *
FROM EMP
WHERE SAL >= 1000    
INTERSECT    
SELECT *
FROM EMP
WHERE SAL <= 1500;

--Q9. 급여가 1000미만이거나 1500 초과인 사원 출력하기
SELECT *
FROM EMP
WHERE SAL < 1000
OR SAL > 1500;

SELECT *
FROM EMP
WHERE NOT(SAL BETWEEN 1000 AND 1500);

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 1500;

SELECT *
FROM EMP
WHERE NOT(SAL >= 1000 AND SAL <= 1500);

SELECT *
FROM EMP
WHERE SAL < 1000    
UNION   
SELECT *
FROM EMP
WHERE SAL > 1500;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL BETWEEN 1000 AND 1500;

SELECT*
FROM EMP
MINUS
(SELECT *
FROM EMP
WHERE SAL >= 1000    
INTERSECT   
SELECT *
FROM EMP
WHERE SAL <= 1500);

--Q10. 추가 수당이 300이거나 500이거나 1400인 사원 출력하기
SELECT *
FROM EMP
WHERE COMM = 300
OR COMM = 500
OR COMM = 1400;

SELECT *
FROM EMP
WHERE COMM IN (300, 500, 1400);

